### ISSUE TITLE
Returning a value of a type with free variables from a match expression causes semantic analyser crash

### ISSUE THREAD

**Issue by nhweston** [inkytonik/cooma#76]
Attempting to compile this program:

```
{
  def f(t : Type, b : Boolean) Option(t) = {
    b match {
      case True(_) => <<None = {}>>
      case False(_) => <<None = {}>>
    }
  }
  { }
}
```

…causes the semantic analyser to crash.

Below is the stack track:

```
Exception in thread "main" org.bitbucket.inkytonik.kiama.relation.NodeNotInTreeException: node not in tree: VarT(Vector(FieldType(None,Idn(IdnUse(Unit))), FieldType(Some,Idn(IdnUse(t)))))
        at org.bitbucket.inkytonik.kiama.relation.TreeRelation.apply(TreeRelation.scala:53)
        at org.bitbucket.inkytonik.kiama.relation.Relation$pair$.unapplySeq(Relation.scala:82)
        at org.bitbucket.inkytonik.cooma.SemanticAnalyser$$anonfun$envout$1.applyOrElse(SemanticAnalyser.scala:323)
        at org.bitbucket.inkytonik.cooma.SemanticAnalyser$$anonfun$envout$1.applyOrElse(SemanticAnalyser.scala:321)
        at org.bitbucket.inkytonik.kiama.attribution.Decorators.$anonfun$chain$5(Decorators.scala:147)
        at org.bitbucket.inkytonik.kiama.attribution.Attribution$CachedAttribute.liftedTree1$1(Attribution.scala:61)
        at org.bitbucket.inkytonik.kiama.attribution.Attribution$CachedAttribute.apply(Attribution.scala:59)
	at org.bitbucket.inkytonik.kiama.attribution.Decorators$Chain.apply(Decorators.scala:88)
	at org.bitbucket.inkytonik.cooma.SemanticAnalyser.unalias(SemanticAnalyser.scala:725)
	at org.bitbucket.inkytonik.cooma.SemanticAnalyser.$anonfun$unaliases$1(SemanticAnalyser.scala:753)
	at scala.collection.immutable.Vector1.map(Vector.scala:1886)
	at scala.collection.immutable.Vector1.map(Vector.scala:375)
	at org.bitbucket.inkytonik.cooma.SemanticAnalyser.unaliases(SemanticAnalyser.scala:753)
	at org.bitbucket.inkytonik.cooma.SemanticAnalyser.unaliasFieldTypes(SemanticAnalyser.scala:792)
	at org.bitbucket.inkytonik.cooma.SemanticAnalyser.unaliasVarT(SemanticAnalyser.scala:807)
	at org.bitbucket.inkytonik.cooma.SemanticAnalyser.unalias(SemanticAnalyser.scala:743)
	at org.bitbucket.inkytonik.cooma.SemanticAnalyser.subtype(SemanticAnalyser.scala:919)
	at org.bitbucket.inkytonik.cooma.SemanticAnalyser.checkExpressionType(SemanticAnalyser.scala:85)
	at org.bitbucket.inkytonik.cooma.SemanticAnalyser$$anonfun$errors$lzycompute$1.applyOrElse(SemanticAnalyser.scala:62)
	at org.bitbucket.inkytonik.cooma.SemanticAnalyser$$anonfun$errors$lzycompute$1.applyOrElse(SemanticAnalyser.scala:39)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:241)
	at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:117)
	at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:104)
	at scala.collection.immutable.Vector.flatMap(Vector.scala:113)
	at org.bitbucket.inkytonik.kiama.util.Messaging$.collectMessages(Messaging.scala:113)
	at org.bitbucket.inkytonik.cooma.SemanticAnalyser.errors$lzycompute(SemanticAnalyser.scala:39)
	at org.bitbucket.inkytonik.cooma.SemanticAnalyser.errors(SemanticAnalyser.scala:38)
	at org.bitbucket.inkytonik.cooma.Driver.checkProgram(Driver.scala:114)
	at org.bitbucket.inkytonik.cooma.Driver.makeast(Driver.scala:86)
	at org.bitbucket.inkytonik.cooma.Driver.compileSource(Driver.scala:57)
	at org.bitbucket.inkytonik.cooma.Driver.compileSource(Driver.scala:16)
	at org.bitbucket.inkytonik.kiama.util.CompilerBase.compileFile(Compiler.scala:123)
	at org.bitbucket.inkytonik.kiama.util.CompilerBase.compileFile$(Compiler.scala:120)
	at org.bitbucket.inkytonik.cooma.Driver.compileFile(Driver.scala:16)
	at org.bitbucket.inkytonik.cooma.Driver.compileFiles(Driver.scala:46)
	at org.bitbucket.inkytonik.cooma.Driver.compileFiles(Driver.scala:16)
	at org.bitbucket.inkytonik.kiama.util.CompilerBase.run(Compiler.scala:104)
	at org.bitbucket.inkytonik.kiama.util.CompilerBase.run$(Compiler.scala:100)
	at org.bitbucket.inkytonik.cooma.ReferenceDriver.run(ReferenceFrontend.scala:47)
	at org.bitbucket.inkytonik.cooma.ReferenceFrontend.interpret(ReferenceFrontend.scala:21)
	at org.bitbucket.inkytonik.cooma.Main$.runMain(Main.scala:32)
	at org.bitbucket.inkytonik.cooma.Main$.main(Main.scala:21)
	at org.bitbucket.inkytonik.cooma.Main.main(Main.scala)
```

This appears to occur in various other situations, all involving unaliasing and subtype or bound checking.

**Comment by inkytonik** [comment]
This is tied up with incomplete handling of type arguments/parameters. Probably quite a bit of work to fix.
