### ISSUE TITLE
Running `test` twice in sbt gets an "address already in use" error

### ISSUE THREAD

**Issue by inkytonik** [inkytonik/cooma#84]
If I run sbt then ‘test’ twice I get bind errors like the following. It looks like something’s not getting closed.

```
java.net.BindException: Address already in use
  | => rat java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:555)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
        at java.base/java.nio.channels.ServerSocketChannel.bind(ServerSocketChannel.java:224)
        at org.http4s.blaze.channel.nio1.NIO1SocketServerGroup.$anonfun$bind$1(NIO1SocketServerGroup.scala:225)
        at scala.util.Try$.apply(Try.scala:210)
        at org.http4s.blaze.channel.nio1.NIO1SocketServerGroup.bind(NIO1SocketServerGroup.scala:224)
        at org.http4s.blaze.channel.nio1.NIO1SocketServerGroup$$anon$1.bind(NIO1SocketServerGroup.scala:86)
        at org.http4s.server.blaze.BlazeServerBuilder.$anonfun$resource$5(BlazeServerBuilder.scala:358)
        at map @ org.http4s.server.blaze.BlazeServerBuilder.mkServerChannel$1(BlazeServerBuilder.scala:355)
        at make @ org.http4s.server.blaze.BlazeServerBuilder.$anonfun$resource$1(BlazeServerBuilder.scala:350)
        at apply @ org.http4s.blazecore.package$.tickWheelResource(package.scala:24)
        at flatMap @ fs2.internal.CompileScope.acquireResource(CompileScope.scala:180)
        at flatMap @ fs2.internal.FreeC$.$anonfun$compile$12(Algebra.scala:511)
        at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
        at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
        at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
        at flatMap @ fs2.internal.CompileScope.$anonfun$acquireResource$4(CompileScope.scala:185)
        at flatten @ fs2.internal.ScopedResource$$anon$1.acquired(ScopedResource.scala:139)
        at flatMap @ fs2.internal.CompileScope.$anonfun$acquireResource$1(CompileScope.scala:183)
        at make @ org.http4s.server.blaze.BlazeServerBuilder.$anonfun$resource$1(BlazeServerBuilder.scala:350)
        at apply @ org.http4s.blazecore.package$.tickWheelResource(package.scala:24)
        at flatMap @ fs2.internal.CompileScope.acquireResource(CompileScope.scala:180)
        at flatMap @ fs2.internal.FreeC$.$anonfun$compile$12(Algebra.scala:511)
        at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
```

**Comment by inkytonik** [comment]
Reproduce with 

```shell
$ sbt
> testOnly *HttpClientTests*
> testOnly *HttpClientTests*
```
